jwt:
  secret: 35018245011Di008F730632f1401E3CD
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
            # 移除路径前缀/user
            - StripPrefix=1
        - id: system-service-api
          uri: lb://system-service
          predicates:
            - Path=/swagger-ui/index.html
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/