jwt:
  secret: 35018245011Di008F730632f1401E3CD
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/**
          #  - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
            # 移除路径前缀/user
          #  - StripPrefix=1
    globalcors:
      # 跨域配置(可以在代码里面处理允许跨域，也可在这里全局处理)
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedHeaders: "*"
          allowCredentials: true
          allowedMethods:
            - GET
            - POST
            - OPTIONS
            - DELETE
            - PUT
            - HEAD
            - PATCH
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# knife4j 网关聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: manual     # discover 自动
    routes:
      - name: 后台服务
        service-name: sysytem-service
        url: /v3/api-docs
    discover:
      # OpenAPI 3.0 规范
      version: openapi3
      enabled: true
      excluded-services:
        # 排除order开头的服务
        - CONFIG.*