jwt:
  secret: 35018245011Di008F730632f1401E3CD
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/**
          #  - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
            # 移除路径前缀/user
          #  - StripPrefix=1
    globalcors:
      # 跨域配置(可以在代码里面处理允许跨域，也可在这里全局处理)
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedHeaders: "*"
          allowCredentials: true
          allowedMethods:
            - GET
            - POST
            - OPTIONS
            - DELETE
            - PUT
            - HEAD
            - PATCH
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/