jwt:
  secret: 35018245011Di008F730632f1401E3CD
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        # 跨域配置(可以在代码里面处理允许跨域，也可在这里全局处理)
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
              - HEAD
              - PATCH
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/**
          #  - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
            # 移除路径前缀/user
          #  - StripPrefix=1
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# knife4j 网关聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    discover:
      # OpenAPI 3.0 规范
      version: openapi3
      enabled: true
      excluded-services:
        # 排除config开头的服务
        - config.*