jwt:
  secret: 35018245011Di008F730632f1401E3CD
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/**
          #  - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
            # 移除路径前缀/user
          #  - StripPrefix=1
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# knife4j 网关聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    discover:
      # OpenAPI 3.0 规范
      version: openapi3
      enabled: true
      excluded-services:
        # 排除config开头的服务
        - config.*